---
# Druid Template variables
druid_monitoring: true
zookeeper_group: "groups[{{ cluster }}-zookeeper]"

druid_user: druid
druid_directory: "/data"
druid_version: "0.21.1"
druid_url: "https://downloads.apache.org/druid/0.21.1/apache-druid-0.21.1-bin.tar.gz"
druid_folder: "{{ druid_directory }}/apache-druid-{{ druid_version }}"
druid_symlink: "{{ druid_directory }}/druid"
druid_path: "{{ druid_symlink }}/"
druid_checksum: "a68c63ddf92a0939315bd8b79fbdd5fae712e888d1a0e0466f0a87a8e8f1270d70fc5dcc0ec64e076391576be29da1cce88f7c5cf725c31418601e4eee8fa354"

#Common Varibles

druid_zookeeper_host: "{{ groups[cluster+'-zookeeper']|join(':2181,')}}:2181"
druid_postgres_user: druid
#druid_postgres_host: "{{ groups['druid-postgres'][0] }}"


druid_default_tmp_dir: "/var/tmp"
druid_gc_logdir: "/var/log/druid/crash_logs"
druid_crash_logdir: "/var/log/druid/crash_logs"
druid_log_dir: "/var/log/druid/"

#Writing request query logs to file 
druid_request_logging_type: "file"

#Druid Extensions

druid_storge_type: "azure"

druid_extensions_list: '"druid-azure-extensions", "graphite-emitter", "postgresql-metadata-storage", "druid-kafka-indexing-service"'

druid_community_extensions:
  - graphite-emitter

# End of druid_extensions

druid_indexing_logs_type: azure
druid_indexing_log_dir: /var/druid/indexing-logs
druid_indexing_storage_type: metadata
druid_indexing_task_basedir: "/var/task"

druid_common_monitors: '"com.metamx.metrics.JvmMonitor","org.apache.druid.java.util.metrics.JvmMonitor"'
druid_common_emitters: '"logging","graphite"'

druid_graphite_prefix: "druid.metric"
druid_whitelist_filepath: "{{ druid_path }}whitelist"

#End of Common variables

#Coordinator Configurations

druid_coordinator_port: 8081
druid_coordinator_service: druid/coordinator

druid_coordinator_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_coordinator_gc_logfile: "{{ druid_crash_logdir }}/gc.coordinator.log"
druid_coordinator_heap_dump_file: "{{ druid_crash_logdir }}/coordinator.hprof"

#Overlord Configurations
druid_overlord_port: 8090
druid_overlord_service: druid/overlord

druid_overlord_heap_size: 2048m
druid_overlord_min_heap_size: 1024m
druid_overlord_max_heap_size: 2048m

druid_overlord_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_overlord_gc_logfile: "{{ druid_crash_logdir }}/gc.overlord.log"
druid_overlord_heap_dump_file: "{{ druid_crash_logdir }}/overlord.hprof"

# Configurations Broker
druid_broker_port: 8082
druid_broker_service: druid/broker

druid_broker_max_direct_size: 2048m

druid_broker_tmp_dir: /var/tmp
druid_broker_gc_logfile: "{{ druid_crash_logdir }}/gc.broker.log"
druid_broker_heap_dump_file: "{{ druid_crash_logdir }}/broker.hprof"

# Historical Configurations

druid_historical_port: 8083
druid_historical_service: druid/historical

druid_historical_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_historical_gc_logfile: "{{ druid_crash_logdir }}/gc.historical.log"
druid_historical_heap_dump_file: "{{ druid_crash_logdir }}/historical.hprof"

druid_historical_monitoring_monitors: '"org.apache.druid.server.metrics.HistoricalMetricsMonitor","com.metamx.metrics.JvmMonitor"'

druid_historical_segmentcache_path: "/var/segmentstore"
druid_historical_cache_size: 3221225472
druid_historical_cache_expiry: 3600000

#Middle Manager

druid_middlemanager_port: 8091
druid_middlemanager_service: druid/middlemanager

druid_middlemanager_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_middlemanager_gc_logfile: "{{ druid_crash_logdir }}/gc.middlemanager.log"
druid_mm_heap_dump_file: "{{ druid_crash_logdir }}/middlemanager.hprof"

druid_middlemanager_peon_segmentcache_path: "/var/segment_cache"
druid_azure_container_name: "telemetry-data-store"

#Router
druid_router_port: 8888
druid_router_service: druid/router

druid_router_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_router_gc_logfile: "{{ druid_crash_logdir }}/gc.router.log"
druid_router_heap_dump_file: "{{ druid_crash_logdir }}/router.hprof"


default_druid_configs:
  raw:
   #Druid Postgres Details
   druid_postgres_db: "druid"
   druid_postgres_host: "{{ postgres.db_url }}"
   druid_postgres_port: "{{ postgres.db_port }}"
   druid_postgres_user: "{{ druid_postgres_user | default('druid@{{ postgres.db_url }}') }}"
   #Druid Azure Details 
   druid_postgres_pass: "{{ dp_vault_druid_postgress_pass }}"
   azure_account_name: "{{ sunbird_druid_storage_account_name }}"
   azure_storage_secret: "{{ sunbird_druid_storage_account_key }}"
   azure_container: "{{ druid_azure_container_name }}"
   #Logging the indexing logs to azure
   druid_log_azure_container: "{{ druid_azure_container_name }}"
   druid_log_azure_folder: "druidlogs"
   #Druid coordinator node configuration
   druid_coordinator_min_heap_size: 1024m
   druid_coordinator_max_heap_size: 2048m
   druid_coordinator_period: PT30S
   druid_coordinator_startDelay: PT30S
   druid_coordinator_balance_strategy: diskNormalized
   #Druid overlord node configuration
   druid_overlord_min_heap_size: 1024m
   druid_overlord_max_heap_size: 2048m
   #Druid broker node configuration
   druid_broker_min_heap_size: 1024m
   druid_broker_max_heap_size: 2048m
   druid_broker_max_direct_size: 2048m
   druid_broker_http_numConnections: 5
   druid_broker_server_http_numThread: 25
   druid_broker_processing_bufferBytes: 536870912
   druid_broker_processing_threads: 2
   druid_broker_processing_num_merge_buffers: 2
   #Druid historical node configuration
   druid_historical_min_heap_size: 2048m
   druid_historical_max_heap_size: 5120m
   druid_historical_max_direct_size: 2560m
   druid_historical_http_numConnections: 5
   druid_historical_server_http_numThread: 25
   druid_historical_processing_bufferBytes: 134217728
   druid_historical_processing_threads: 2
   druid_historical_enable_cache: true
   druid_historical_segmentcache_size: 10000000000
   druid_historical_segmentcache_locations__count: 10  # deliberate double underscore to indicate that this does not map to a druid config
   druid_historical_server_maxsize: 120000000000
   druid_historical_processing_num_merge_buffers: 2
   druid_query_ondiskstorage_enabled: true
   druid_historical_maxMergingDictionarySize: 100000000
   druid_historical_segmentcache_numloadingthreads: 4
   druid_historical_segmentcache_path: "/var/segmentstore"
   druid_historical_cache_size: 3221225472
   druid_historical_cache_expiry: 3600000
   druid.query.groupBy.maxOnDiskStorage: 10737418240
   #Druid middlemanager configuration
   druid_middlemanager_min_heap_size: 128m
   druid_middlemanager_max_heap_size: 128m
   druid_middlemanager_worker_cap: 8
   druid_mm_java_opts_array: "-server -Xmx1024m -XX:MaxDirectMemorySize=512m -XX:+UseG1GC -XX:HeapDumpPath={{ druid_mm_heap_dump_file }} -XX:MaxGCPauseMillis=100 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
   druid_middlemanager_peon_server_http_numThread: 25
   druid_middlemanager_peon_processing_bufferBytes: 104857600
   druid_middlemanager_peon_processing_num_merge_buffers: 2
   druid_middlemanager_peon_processing_threads: 2
   druid_middlemanager_peon_server_maxsize: 0
   druid_indexing_queue_startDelay: PT30S
   druid_router_min_heap_size: 1024m
   druid_router_max_heap_size: 1024m
   druid_router_http_numConnections: 50
   druid_router_http_readTimeout: PT5M
   druid_router_http_numMaxThreads: 100
   druid_server_http_numThreads: 100
   druid_router_managementProxy_enabled: true
   druid_historical_maxOnDiskStorage: 10737418240
  rollup:
   #Druid Postgres Details
   druid_postgres_db: "druid"
   druid_postgres_host: "{{ postgres.db_url }}"
   druid_postgres_port: "{{ postgres.db_port }}"
   druid_postgres_user: "{{ druid_postgres_user | default('druid@{{ postgres.db_url }}') }}"
   #Druid Azure Details
   druid_postgres_pass: "{{ dp_vault_druid_postgress_pass }}"
   azure_account_name: "{{ sunbird_druid_storage_account_name }}"
   azure_storage_secret: "{{ sunbird_druid_storage_account_key }}"
   azure_container: "{{ druid_azure_container_name }}"
   #Logging the indexing logs to azure
   druid_log_azure_container: "{{ druid_azure_container_name }}"
   druid_log_azure_folder: "druidlogs"
   druid_coordinator_min_heap_size: 128m
   druid_coordinator_max_heap_size: 128m
   druid_coordinator_period: PT30S
   druid_coordinator_startDelay: PT30S
   druid_coordinator_balance_strategy: cost
   #Druid overlord node configuration
   druid_overlord_min_heap_size: 256m
   druid_overlord_max_heap_size: 256m
   #Druid broker node configuration
   druid_broker_min_heap_size: 128m
   druid_broker_max_heap_size: 128m
   druid_broker_max_direct_size: 700m
   druid_broker_http_numConnections: 5
   druid_broker_server_http_numThread: 25
   druid_broker_processing_bufferBytes: 134217728
   druid_broker_processing_threads: 2
   druid_broker_processing_num_merge_buffers: 2
   #Druid historical node configuration
   druid_historical_min_heap_size: 1048m
   druid_historical_max_heap_size: 1048m
   druid_historical_max_direct_size: 800m
   druid_historical_http_numConnections: 5
   druid_historical_server_http_numThread: 25
   druid_historical_processing_bufferBytes: 134217728
   druid_historical_processing_threads: 2
   druid_historical_enable_cache: false
   druid_historical_segmentcache_size: 2000000000
   druid_historical_segmentcache_locations__count: 5  # deliberate double underscore to indicate that this does not map to a druid config
   druid_historical_server_maxsize: 10000000000
   druid_historical_processing_num_merge_buffers: 2
   druid_query_ondiskstorage_enabled: false
   druid_historical_segmentcache_numloadingthreads: 4
   druid_historical_segmentcache_path: "/var/segmentstore"
   druid_historical_cache_size: 3221225472
   druid_historical_cache_expiry: 3600000
   #Druid middlemanager configuration
   druid_middlemanager_min_heap_size: 128m
   druid_middlemanager_max_heap_size: 128m
   druid_middlemanager_worker_cap: 4
   druid_mm_java_opts_array: "-server -Xmx900m -XX:+UseG1GC -XX:HeapDumpPath={{ druid_mm_heap_dump_file }} -XX:MaxGCPauseMillis=100 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
   druid_middlemanager_peon_server_http_numThread: 25
   druid_middlemanager_peon_processing_bufferBytes: 25000000
   druid_middlemanager_peon_processing_threads: 2
   druid_middlemanager_peon_processing_num_merge_buffers: 2
   druid_middlemanager_peon_server_maxsize: 0
   druid_indexing_queue_startDelay: PT30S
   druid_router_min_heap_size: 1g
   druid_router_max_heap_size: 1g
   druid_router_http_numConnections: 50
   druid_router_http_readTimeout: PT5M
   druid_router_http_numMaxThreads: 100
   druid_server_http_numThreads: 100
   druid_router_managementProxy_enabled: true

enable_druid_sql: true
